# Generated by Django 2.2.3 on 2019-07-09 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='username'),
        ),
    ]
