dist: xenial

addons:
  postgresql: "10.8"

services: postgresql

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y postgresql-10 postgresql-client-10

env:
  - DATABASE_URL=psql://postgres@127.0.0.1:5432/test USE_DOCKER=False

language: python

python:
  - "3.6.7"

install:
  - pip install -r requirements/local.txt
  - pip install -r requirements/test.txt

before_script:
  - psql --version
  - psql -c 'CREATE DATABASE test;' -U postgres

script:
  - ./manage.py migrate
  - flake8
  - cd django_rewrite/
  - pytest

after-success:
  - coveralls
