# Generated by Django 2.2.3 on 2019-07-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='vote',
            field=models.SmallIntegerField(choices=[(1, 'UP'), (-1, 'DOWN')]),
        ),
    ]
